### ISSUE TITLE
highlight.js style won't change

### ISSUE THREAD

**Issue by biccio** [Junyi-99/hugo-theme-anubis2#68]
Thank you for this precious theme, it's great work!
I'm having troubles with highlights.js colors, apparently changing the string on config file has no effect, at least for me. This is what  I tried:

```
[markup.highlight]
anchorLineNos      = false
codeFences         = true
style              = '1c-light'
tabWidth           = 4

```
or any other style that are not `base16snazzy`, they won't work either. 
Am I doing something wrong?

Thank you!

**Comment by Junyi-99** [comment]
Hi @biccio, thanks for the love for this theme!

I’ll look into it when I have some time, which shouldn’t be long!

**Comment by Junyi-99** [comment]
Hi @biccio, hope you are doing well. 

The issue is that the documentation incorrectly describes `Highlight.js`, whereas Hugo actually uses `Chroma` as a compile-time syntax highlighter.

To explore all available Chroma themes, you can visit the [Chroma Playground](https://swapoff.org/chroma/playground/).

We appreciate your feedback and will work on rectifying the documentation.

Best regards,
Junyi.
